addSbtPlugin("com.github.cb372"  % "sbt-explicit-dependencies" % "0.2.10")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"              % "0.14.10")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"                % "1.5.0")
addSbtPlugin("com.tapad"         % "sbt-docker-compose"        % "1.0.35")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"       % "1.8.0")
